### ISSUE TITLE
[Windows] Window not responding when not in focus

### ISSUE THREAD

**Issue by CryZe** [rust-windowing/winit#1384]
When the window is not in focus, at least on Windows and on the [latest master](https://github.com/rust-windowing/winit/commit/09c4ed0694afdcec4f9fb0a3fbd6e8b51dca5833) the window gets marked as "not responding" every 10 seconds or so. This does not happen on 0.20.0.

**Comment by CryZe** [comment]
Considering there aren't many changes since 0.20.0, the regression was likely caused by https://github.com/rust-windowing/winit/commit/6a330a2894873d29fbbfdeebfc1a215577213996

**Comment by CryZe** [comment]
If the commit actually fixes some bug though, it could also just be that it reveals a bug in wgpu?!

**Comment by Osspial** [comment]
I've confirmed that this is a bug on Winit's end that was caused by that fix, but it's not entirely clear to me how it's happening. I'll do some investigation and get a fix in.

**Comment by filnet** [comment]
Could be fixed by https://github.com/rust-windowing/winit/pull/1461.

**Comment by filnet** [comment]
We have pushed a number of critical fixes for Windows. Please retest on master.

**Comment by Dooskington** [comment]
Was running into this issue, on Windows 10 64 bit. 😢 
Every few seconds, window stops responding, "refreshes", and is back to normal again. I tried on master, and it has somewhat improved, but it is still not quite fixed yet.

Now, the window doesn't stop responding, but the close button gets highlighted, the event loop seems to speed up for a little while, then a Resize event gets fired. Then things go back to normal for a few seconds. Then, the same thing repeats.

**Comment by Osspial** [comment]
@Dooskington I'm not able to reproduce that with the standard `window` example. What do you have the event loop's `control_flow` set to? Is there an example that reproduces the issue you're running into reliably?

**Comment by filnet** [comment]
If the issue involves Poll mode and request_redraw then it could be a duplicate of https://github.com/rust-windowing/winit/issues/1477

On Windows 10: `cargo run --example contrrol_flow`

Then with the focus, press `R` to toggle on `request_redraw` from `MainEventsCleared` and press `3` to switch to Poll mode.
Trigger no events for more than 5 seconds (with and without the focus) to see the issue.

I can also see the close button getting highlighted for a brief moment.
The Windows task manager shows the process as not responding.

**Comment by Dooskington** [comment]
I am indeed using control flow Poll, and calling request_redraw from MainEventsCleared.

**Comment by filnet** [comment]
> I am indeed using control flow Poll, and calling request_redraw from MainEventsCleared.

So this issue is a duplicate of https://github.com/rust-windowing/winit/issues/1477

**Comment by Osspial** [comment]
I'm gonna close this issue then, since the original issue has been resolved.
